### ISSUE TITLE
Fix truecolor-rainbow infinite blue line.

### ISSUE THREAD

**Issue by TimoNotThy** [bahamas10/dotfiles#2]
https://github.com/bahamas10/dotfiles/blob/1e8b8827f6b9bbd89191e0df3b7764055de7f645/bashrc#L316

Change the final echo to echo -e "\033[0m" to prevent the infinite blue line.
![image](https://github.com/user-attachments/assets/ee6cf423-dc4d-47f8-b700-cab341fe80af)
This is the result:
![image](https://github.com/user-attachments/assets/8042344b-ec89-4829-930c-118057690c8d)

**Comment by bahamas10** [comment]
noted, ty
